# Generated by Django 2.2.7 on 2020-07-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200705_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, 'تائید نشده'), (1, 'تائید شد')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.IntegerField(choices=[(1, 'منوی فرعی'), (0, 'منوی اصلی')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='sex',
            field=models.IntegerField(choices=[(1, 'آقا'), (0, 'خانم')], default=0, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ads',
            field=models.BooleanField(default=0, null=True, verbose_name='تبلیغات'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='form',
            field=models.BooleanField(default=0, null=True, verbose_name='فرم'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='moshtari',
            field=models.BooleanField(default=0, null=True, verbose_name='باشگاه مشترکین'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='protable',
            field=models.BooleanField(default=0, null=True, verbose_name='کاربران'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='safahat',
            field=models.BooleanField(default=0, null=True, verbose_name='صفحات'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='task_manegar',
            field=models.BooleanField(default=0, null=True, verbose_name='مدیریت وظایف'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='video',
            field=models.BooleanField(default=0, null=True, verbose_name='ویدیو'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='status',
            field=models.IntegerField(choices=[(2, 'صفحه'), (1, 'ادرس'), (0, 'دسته بندی')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='status',
            field=models.IntegerField(choices=[(0, 'در حال انجام'), (3, 'انجام شده'), (1, 'برای آینده')], default=0, verbose_name='وضعیت'),
        ),
    ]
