# Generated by Django 2.2.7 on 2020-07-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200705_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.IntegerField(choices=[(0, 'منوی اصلی'), (1, 'منوی فرعی')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dads',
            field=models.BooleanField(default=1, verbose_name='دسترسی به تبلیغات'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dcategory',
            field=models.BooleanField(default=1, verbose_name='دسترسی به دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dcomment',
            field=models.BooleanField(default=1, verbose_name='دسترسی به کامنت ها'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dform',
            field=models.BooleanField(default=1, verbose_name='دسترسی به فرم ساز'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dhavadaran',
            field=models.BooleanField(default=1, verbose_name='دسترسی به هواداران'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dkarbaran',
            field=models.BooleanField(default=1, verbose_name='دسترسی به کاربران'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dlink',
            field=models.BooleanField(default=1, verbose_name='دسترسی به لینک ها'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dmenu',
            field=models.BooleanField(default=1, verbose_name='دسترسی به منوساز'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dmultimedia',
            field=models.BooleanField(default=1, verbose_name='دسترسی به مالتی مدیا'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dpost',
            field=models.BooleanField(default=1, verbose_name='دسترسی به پست ها'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dsafahat',
            field=models.BooleanField(default=1, verbose_name='دسترسی به صفحات اضافی'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dsetting',
            field=models.BooleanField(default=1, verbose_name='دسترسی به تنظیمات سایت'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dslider',
            field=models.BooleanField(default=1, verbose_name='دسترسی به اسلایدرها'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dtaskmanager',
            field=models.BooleanField(default=1, verbose_name='دسترسی به مدیریت وظایف'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dthemeeditor',
            field=models.BooleanField(default=1, verbose_name='ویرایش قالب'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='dvideo',
            field=models.BooleanField(default=1, verbose_name='دسترسی به ویدیو'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='image',
            field=models.ImageField(default='user.png', upload_to='images/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ads',
            field=models.BooleanField(default=1, verbose_name='تبلیغات'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='form',
            field=models.BooleanField(default=1, verbose_name='فرم'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='moshtari',
            field=models.BooleanField(default=1, verbose_name='باشگاه مشترکین'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='protable',
            field=models.BooleanField(default=1, verbose_name='کاربران'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='safahat',
            field=models.BooleanField(default=1, verbose_name='صفحات'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='task_manegar',
            field=models.BooleanField(default=1, verbose_name='مدیریت وظایف'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='video',
            field=models.BooleanField(default=1, verbose_name='ویدیو'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='status',
            field=models.IntegerField(choices=[(0, 'دسته بندی'), (2, 'صفحه'), (1, 'ادرس')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='status',
            field=models.IntegerField(choices=[(1, 'برای آینده'), (3, 'انجام شده'), (0, 'در حال انجام')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='time',
            name='status',
            field=models.IntegerField(choices=[(0, 'در حال وظیفه'), (1, 'خارج از وظیفه')], default=0, verbose_name='وضعیت'),
        ),
    ]
