# Generated by Django 2.2.7 on 2020-07-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200706_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(1, 'تائید شد'), (0, 'تائید نشده')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.FileField(default='logo.jpg', upload_to='logo/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='status',
            field=models.IntegerField(choices=[(1, 'ادرس'), (2, 'صفحه'), (0, 'دسته بندی')], default=0, verbose_name='وضعیت'),
        ),
    ]
