# Generated by Django 2.2.7 on 2020-07-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200720_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_manegar',
            old_name='cretat_time',
            new_name='created_time',
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, 'تائید نشده'), (1, 'تائید شد')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='status',
            field=models.IntegerField(choices=[(1, 'ادرس'), (0, 'دسته بندی'), (2, 'صفحه')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='status',
            field=models.IntegerField(choices=[(1, 'درحال انجام'), (0, 'انجام نشده'), (3, 'انجام شده')], default=0, verbose_name='وضعیت'),
        ),
    ]
