# Generated by Django 2.2.7 on 2020-08-12 08:35

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_theme_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Ads', 'verbose_name_plural': 'Ads'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='olaviat',
        ),
        migrations.AlterField(
            model_name='ads',
            name='EXdate',
            field=django_jalali.db.models.jDateField(verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(upload_to='ads/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='blog.Category', verbose_name='Mother category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pcount',
            field=models.IntegerField(default=0, verbose_name='Number of posts'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, 'تائید نشده'), (1, 'تائید شد')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='status',
            field=models.IntegerField(choices=[(0, 'دسته بندی'), (2, 'صفحه'), (1, 'ادرس')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='status',
            field=models.IntegerField(choices=[(1, 'درحال انجام'), (0, 'انجام نشده'), (3, 'انجام شده')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='time',
            name='status',
            field=models.IntegerField(choices=[(0, 'در حال وظیفه'), (1, 'خارج از وظیفه')], default=0, verbose_name='وضعیت'),
        ),
    ]
