# Generated by Django 2.2.7 on 2020-09-26 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200813_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=400, verbose_name='url')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='html',
            field=models.CharField(default='category.html', max_length=200, verbose_name='Category File Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='htmlpost',
            field=models.CharField(default='post.html', max_length=200, verbose_name='File Name Read More of This Ccategory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category', to='blog.Category', verbose_name='Mother Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pcount',
            field=models.IntegerField(default=0, verbose_name='Number of Posts'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (0, 'Not confirmed')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='copen',
            name='copeni',
            field=models.IntegerField(default=0, verbose_name='Percentage of Coupons'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('number', 'Number'), ('password', 'Password'), ('text', 'Text')], default='text', max_length=10, verbose_name='Type of Field'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], default=0, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='portable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Userportable', to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='com',
            field=models.BooleanField(default=0, verbose_name='Users Can Comment'),
        ),
        migrations.AlterField(
            model_name='safahat',
            name='html',
            field=models.CharField(default='page.html', max_length=200, verbose_name='Format File Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='introduction',
            field=models.TextField(verbose_name='Short Introduction'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='moshtari',
            field=models.BooleanField(default=1, verbose_name='Customers Club'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='status',
            field=models.IntegerField(choices=[(2, 'Page'), (1, 'Address'), (0, 'Category')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='status',
            field=models.IntegerField(choices=[(1, 'Completing'), (0, 'Incomplete!'), (3, 'Complete!')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Format Name'),
        ),
        migrations.AlterField(
            model_name='time',
            name='in_date',
            field=models.DateField(verbose_name='Login Date'),
        ),
        migrations.AlterField(
            model_name='time',
            name='out_date',
            field=models.DateField(null=True, verbose_name='Logout Date'),
        ),
    ]
