# Generated by Django 2.2.7 on 2020-09-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200926_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='status',
            field=models.IntegerField(choices=[(1, 'Address'), (2, 'Page'), (0, 'Category')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='status',
            field=models.IntegerField(choices=[(3, 'Complete!'), (0, 'Incomplete!'), (1, 'Completing')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='time',
            name='status',
            field=models.IntegerField(choices=[(1, 'Out of Duty'), (0, 'On Duty')], default=0, verbose_name='Status'),
        ),
    ]
