# Generated by Django 2.2.7 on 2020-09-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200927_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='safahat',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portable',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], default=0, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='status',
            field=models.IntegerField(choices=[(1, 'Address'), (0, 'Category'), (2, 'Page')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='status',
            field=models.IntegerField(choices=[(3, 'Complete!'), (1, 'Completing'), (0, 'Incomplete!')], default=0, verbose_name='Status'),
        ),
    ]
