# Generated by Django 2.2.7 on 2020-10-01 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20201001_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portable',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], default=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='status',
            field=models.IntegerField(choices=[(2, 'Page'), (1, 'Address'), (0, 'Category')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subtickets',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 1, 9, 13, 46, 886267), null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 1, 9, 13, 46, 886267), null=True, verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='status',
            field=models.IntegerField(choices=[(1, 'In progress'), (0, 'To Do'), (3, 'Done!')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
