# Generated by Django 2.2.7 on 2020-10-01 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20201001_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtickets',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.IntegerField(choices=[(0, 'Primary Menu'), (1, 'Secondry Menu')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='status',
            field=models.IntegerField(choices=[(1, 'Address'), (0, 'Category'), (2, 'Page')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 1, 9, 17, 33, 148334), null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 1, 9, 17, 33, 148334), null=True, verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='status',
            field=models.IntegerField(choices=[(3, 'Done!'), (0, 'To Do'), (1, 'In progress')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='time',
            name='status',
            field=models.IntegerField(choices=[(0, 'On Duty'), (1, 'Out of Duty')], default=0, verbose_name='Status'),
        ),
    ]
